spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: twice333
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.young.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080
